version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  bookmedik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmedik
    environment:
      DB_HOST: mariadb
      DB_NAME: bookmedik
      DB_USER: root
      DB_PASS: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
